# ./docker-compose.yml

version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: questionnaire
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
    ports:
      - "9906:3306"
  web:
    image: php:7.2.2-apache
    container_name: php_web_questionnaire
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
      - ./.docker/vhost/vhost.conf:/etc/apache2/sites-available/000-default.conf:ro
      - ./.docker/vhost/vhost.conf:/etc/apache2/sites-enabled/000-default.conf:ro
    extra_hosts:
    - "questionnaire:127.0.0.1"
    hostname: questionnaire
    domainname: questionnaire 
    ports:
      - "80:80"
    stdin_open: true
    tty: true